import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import Link from "next/link";
import Projects from "../components/Projects";

export default function Home() {
  const [offset, setOffset] = useState(0);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-mono h-screen bg-center bg-cover bg-[url('https://images.unsplash.com/photo-1597226290016-764e1f4767dd?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80')] ">
        <div
          className={
            "transition-all duration-200 flex flex-col overflow-hidden " +
            (offset > 40 ? "rounded-lg p-4" : "")
          }
        >
          <nav
            className={
              "flex justify-between text-white bg-slate-900 py-2 px-4 fixed transition-all duration-200  " +
              (offset > 40 ? "rounded-t-lg p-4 w-[calc(100%-2rem)]" : "w-full")
            }
          >
            <span>{"> "}cdeli.dev</span>
            <div className="md:flex space-x-4 hidden">
              <Link href={"#"}>Accueil</Link>
              <Link href={"#"}>Projets</Link>
              <Link href={"#"}>Expérience</Link>
              <Link href={"#"}>Contact</Link>
            </div>
            <button className="md:hidden">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={1.5}
                stroke="currentColor"
                className="w-6 h-6"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"
                />
              </svg>
            </button>
          </nav>
          <div
            className={
              "h-full w-full bg-slate-800/80 mt-[40px] overflow-y-scroll transition-all duration-200 backdrop-blur " +
              (offset > 40
                ? "max-h-[calc(100vh-2rem-40px)] rounded-b-lg"
                : "max-h-[calc(100vh-40px)]")
            }
            onScroll={(e) => {
              // @ts-ignore
              setOffset(e.target.scrollTop);
            }}
          >
            <div className="h-[200vh]">
              <div className="flex md:flex-row flex-col md:space-x-4 md:space-y-0 space-y-4 px-4 pt-4 group">
                <div className="flex flex-col justify-between md:w-3/5 w-full md:h-72 bg-purple-800/50 text-white rounded-lg transition-all duration-200 p-4">
                  <div>
                    <div className="font-mono text-2xl">
                      Je suis Célien, <br />
                      développeur web fullstack
                    </div>
                    <div className="mt-4">
                      Je développe des sites avec de nombreuses technologies et
                      outils tels que{" "}
                      <span className="group-hover:text-red-500 transition-all duration-200">
                        Laravel
                      </span>
                      ,{" "}
                      <span className="group-hover:text-blue-500 transition-all duration-200">
                        NextJS
                      </span>{" "}
                      ou encore{" "}
                      <span className="group-hover:text-green-500 transition-all duration-200">
                        Shopify Liquid
                      </span>
                    </div>
                  </div>
                  <div className="mt-6 flex space-x-4">
                    <Link
                      href="#"
                      className="block bg-slate-900 text-white px-4 py-2 rounded-lg w-max"
                    >
                      Contactez-moi
                    </Link>
                    <Link
                      href="https://molecul.fr"
                      className="block bg-purple-600 text-white px-4 py-2 rounded-lg w-max"
                    >
                      Besoin d{"'"}un site ?
                    </Link>
                  </div>
                </div>
                <div className="md:w-2/5 w-full h-72 bg-blue-400/50 rounded-lg md:hover:w-3/4 transition-all duration-200 bg-center bg-cover bg-[url('/zach-wear-PNeM21iaAhc-unsplash.jpg')]"></div>
              </div>
              <div className="w-[calc(100%-2rem)] text-center p-8 bg-slate-800/75 m-4 rounded-lg text-2xl text-white">
                Projets développés
              </div>
              <Projects />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
